#!/bin/bash

NARG="$#"

# Wrapper script for mfold-3.6

# Environment variables
# A link is needed in /usr/local/share pointing towards /opt/apps/AL9/mfold/share/mfold
export PATH=/opt/apps/AL9/mfold/bin:$PATH
export DATAPATH=/opt/apps/AL9/RNAstructure/data_tables  # For converting from CT into dot-bracket
CT2DOT=/opt/apps/AL9/RNAstructure/exe/ct2dot   # ct2dot program from https://rna.urmc.rochester.edu/RNAstructure.html
VARNA_JAR=/usr/local/bin/VARNAv3-93.jar

echo "This is the mrq1 wrapper script for mfold execution"
ARG="$(echo $*)"
PREFIX=$(echo ${ARG} | sed -n 's/.*SEQ=\([^ ]*\).*/\1/p')
PREFIX=${PREFIX/.*/}

# Execute
echo "Executing mfold ..."
mfold $* 
echo "Finished mfold ..."

if [ $NARG -eq 0 ]; then exit; fi 

# Converting CT into DB and removing ps and pdf files and creating VARNA PNG files
for file in $(ls  ${PREFIX}_*.ct)
do
	${CT2DOT} $file  1  ${file/.ct/.dbn} >& /dev/null
	rm -f ${file/.ct/.ps}
	rm -f ${file/.ct/.pdf}
	java -cp ${VARNA_JAR} fr.orsay.lri.varna.applications.VARNAcmd \
  -resolution 4.0 \
  -bpstyle lw \
  -spaceBetweenBases 1.2 \
  -algorithm naview \
  -i ${file/.ct/.dbn} \
  -o ${file/.ct/.png} 
done
echo "dot-bracket and varna png files generated by the wrapper script"

